# Chapter 6 Assignment & Case Study

## Data Handling - Assignment(Numpy Lab)

### n_size_ndarray_creation
- 함수목적 : n의 제곱수로 2 dimentional array를 생성하는 ndarray.
- Args(n : 생성하고자 하는 ndarray의 row와 column의 개수, dtype : 생성하려는 ndarray의 data type (np.int))
- Returns : row와 column의 길이가 n인 two dimentional ndarray로 X[0,0]은 0으로 순차적으로 X[n-1,n-1]은 n^2-1이 할당됨

In [2]:
import numpy as np

In [3]:
def n_size_ndarray_creation(n, dtype=np.int):
    return np.array(range(n**2), dtype=dtype).reshape(n,n)

In [4]:
n_size_ndarray_creation(3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### zero_or_one_or_empty_ndarray
- 함수목적 : shape이 지정된 크기의 ndarray를 생성, 이때 행렬의 element는 type에 따라 0, 1 또는 empty로 생성됨.
- Args(shape: 생성할려는 ndarray의 shape, type: 생성되는 element들의 값을 지정함0은 0, 1은 1, 99는 empty 타입으로 생성됨, dtype: 생성하려는 ndarray의 data type (np.int))
- Returns : shape의 크기로 생성된 ndarray로 type에 따라 element의 내용이 변경됨

In [ ]:
def zero_or_one_or_empty_ndarray1(shape, type=0, dtype=np.int):
    if type == 0:
        return  np.zeros(shape=shape, dtype=dtype)
    if type == 1:
        return np.ones(shape=shape, dtype=dtype)
    if type == 99:
        return np.empty(shape=shape, dtype=dtype)

In [5]:
def zero_or_one_or_empty_ndarray(shape, type=0, dtype=np.int):
    dic = {0: np.zeros(shape=shape, dtype=dtype), 1: np.ones(shape=shape, dtype=dtype), 99:np.empty(shape=shape, dtype=dtype)}
    return dic[type]

In [6]:
zero_or_one_or_empty_ndarray(shape=(2,2), type=1)

array([[1, 1],
       [1, 1]])

In [14]:
zero_or_one_or_empty_ndarray(shape=(3,3), type=99)
#임의의수 생성

array([[-876235504,        479, -876298192],
       [       479, 1786053168,          0],
       [1786053168,          0, -881358800]])

### change_shape_of_ndarray
- 함수목적 : 입력된 ndarray X를 n_row의 값을 row의 개수로 지정한 matrix를 반환함. 이때 입력하는 X의 size는 2의 거듭제곱수로 전제함. 만약 n_row과 1일 때는 matrix가 아닌 vector로 반환함.
- Args(X: 입력하는 ndarray, n_row: 생성할려는 matrix의 row의 개수)
- Returns : row의 개수가 n_row인 Matrix 또는 Vector, n_row가 1이면 Vector 값으로 반환함

In [15]:
def change_shape_of_ndarray(X, n_row):
    return X.flatten() if n_row==1 else X.reshape(n_row, -1)

In [21]:
X = np.ones((32,32), dtype=np.int)
X

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ..., 
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [22]:
change_shape_of_ndarray(X, 1)

array([1, 1, 1, ..., 1, 1, 1])

### concat_ndarray
- 함수목적 : 입력된 ndarray X_1과 X_2를 axis로 입력된 축을 기준으로 통합하여 반환하는 함수, X_1과 X_2는 matrix 또는 vector 임, 그러므로 vector 일 경우도 처리할 수 가 있어야 함, axis를 기준으로 통합할 때, 통합이 불가능하면 False가 반환됨. 단 X_1과 X_2 Matrix, Vector 형태로 들어왔다면, Vector를 row가 1개인 Matrix로 변환하여 통합이 가능한지 확인할 것
- Args(X_1: 입력하는 ndarray, X_2: 입력하는 ndarray, axis: 통합의 기준이 되는 축 0 또는 1임)
- Returns : X_1과 X_2과 통합된 matrix 타입의 ndarray

In [23]:
def concat_ndarray(X_1, X_2, axis):
    try:
        if X_1.ndim == 1:
            X_1 = X_1.reshape(1, -1)
        if X_2.ndim == 1:
            X_2 = X_2.reshape(1, -1)
        return np.concatenate((X_1, X_2), axis=axis)
    except ValueError as e:
        return False

In [24]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
concat_ndarray(a, b, 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

### normalize_ndarray
- 함수목적 : 입력된 Matrix 또는 Vector를 ndarray X의 정규화된 값으로 변환하여 반환함, 이때 정규화 변환 공식 Z = (X - X의평균) / X의 표준편차로 구성됨, X의 평균과 표준편차는 axis를 기준으로 axis 별로 산출됨, Matrix의 경우 axis가 0 또는 1일 경우, row 또는 column별로 Z value를 산출함, axis가 99일 경우 전체 값에 대한 normalize 값을 구함.
- Args(X: 입력하는 ndarray, axis: normalize를 구하는 기준이 되는 축으로 0, 1 또는 99임, 단 99는 axis 구분 없이 전체값으로 평균과 표준편차를 구함, dtype: data type으로 np.float32로 구정)
- Returns : 정규화된 ndarray

In [29]:
def normalize_ndarray(X, axis=99, dtype=np.float32):
    X = X.astype(np.float32)
    n_row, n_column = X.shape
    if axis == 99:
        x_mean = np.mean(X)
        x_std = np.std(X)
        Z = (X - x_mean) / x_std
    if axis == 0:
        x_mean = np.mean(X, 0).reshape(1, -1)
        x_std = np.std(X, 0).reshape(1, -1)
        Z = (X - x_mean) / x_std
    if axis == 1:
        x_mean = np.mean(X, 1).reshape(n_row, -1)
        x_std = np.std(X, 1).reshape(n_row, -1)
        Z = (X - x_mean) / x_std
        
    return Z

In [32]:
X = np.arange(12, dtype=np.float32).reshape(6,2)
X

array([[  0.,   1.],
       [  2.,   3.],
       [  4.,   5.],
       [  6.,   7.],
       [  8.,   9.],
       [ 10.,  11.]], dtype=float32)

In [27]:
normalize_ndarray(X)

array([[-1.59325504, -1.3035723 ],
       [-1.01388955, -0.72420681],
       [-0.43452409, -0.14484136],
       [ 0.14484136,  0.43452409],
       [ 0.72420681,  1.01388955],
       [ 1.3035723 ,  1.59325504]], dtype=float32)

In [30]:
normalize_ndarray(X, 1)

array([[-1.,  1.],
       [-1.,  1.],
       [-1.,  1.],
       [-1.,  1.],
       [-1.,  1.],
       [-1.,  1.]], dtype=float32)

In [31]:
normalize_ndarray(X, 0)

array([[-1.46385002, -1.46385002],
       [-0.87831002, -0.87831002],
       [-0.29277   , -0.29277   ],
       [ 0.29277   ,  0.29277   ],
       [ 0.87831002,  0.87831002],
       [ 1.46385002,  1.46385002]], dtype=float32)

### save_ndarray
- 함수목적 : 입력된 ndarray X를 argument filename으로 저장함
- Args(X: 입력하는 ndarray, filename: 저장할려는 파일이름)

In [33]:
def save_ndarray(X, filename="test.npy"):
    file_test = open(filename, "wb")
    np.save(X, file_test)

### boolean_index
- 함수목적 : 입력된 ndarray X를 String type의 condition 정보를 바탕으로 해당 컨디션에 해당하는 ndarray X의 index 번호를 반환함, 단 이때, str type의 조건인 condition을 코드로 변환하기 위해서는 eval(str("X") + condition)를 사용할 수 있음
- Args(X: 입력하는 ndarray, condition: string type의 조건 (">3", "== 5", "< 15")
- Returns : 조건에 만족하는 ndarray X의 index

In [35]:
def boolean_index(X, condition):
    codition = eval(str("X") + condition)
    return np.where(condition)

In [42]:
X = np.arange(32, dtype=np.float32)
X

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.], dtype=float32)

In [41]:
X > 6

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True], dtype=bool)

In [43]:
np.where(X > 6)

(array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
        24, 25, 26, 27, 28, 29, 30, 31], dtype=int64),)

### find_nearest_value
- 함수목적 : 입력된 vector type의 ndarray X에서 target_value와 가장 차이가 작게나는 element를 찾아 리턴함, 이때 X를 list로 변경하여 처리하는 것은 실패로 간주함.
- Args(X: 입력하는 vector type의 ndarray, target_value : 가장 유사한 값의 기준값이 되는 값)
- Returns : target_value와 가장 유사한 값

In [44]:
def find_nearest_value(X, target_value):
    return X[np.argmin(np.abs(X - target_value))]

In [50]:
X = np.random.uniform(0, 1, 5)
target_value = 0.3

In [51]:
X

array([ 0.91321064,  0.92911359,  0.91319335,  0.48595309,  0.32924403])

In [53]:
np.abs(X - target_value)

array([ 0.61321064,  0.62911359,  0.61319335,  0.18595309,  0.02924403])

In [55]:
np.argmin(np.abs(X - target_value))

4

In [56]:
X[4]

0.32924403234145572

In [52]:
find_nearest_value(X, target_value)

0.32924403234145572

### get_n_largest_values
- 함수목적 : 입력된 vector type의 ndarray X에서 큰 숫자 순서대로 n개의 값을 반환함.
- Args(X: vector type의 ndarray, n: 반환할려는 element의 개수)
- Returns : ndarray X의 element중 큰 숫자 순서대로 n개 값이 반환됨 ndarray

In [61]:
def get_n_largest_values(X, n):
    return X[np.argsort(X[::-1])[:n]]

In [64]:
X = np.random.uniform(0, 1, 5)

In [69]:
X

array([ 0.61121964,  0.62319633,  0.05235451,  0.10494262,  0.40465624])

In [70]:
np.argsort(X)

array([2, 3, 4, 0, 1], dtype=int64)

In [71]:
np.argsort(X)[::-1]

array([1, 0, 4, 3, 2], dtype=int64)

In [72]:
X[np.argsort(X)[::-1]]

array([ 0.62319633,  0.61121964,  0.40465624,  0.10494262,  0.05235451])

In [73]:
X[np.argsort(X)[::-1]][:3]

array([ 0.62319633,  0.61121964,  0.40465624])

In [66]:
get_n_largest_values(X, 3)

array([ 0.05235451,  0.62319633,  0.61121964])