# Data Handling - Data cleansing

## Data quality problems
- 데이터의 최대/최소가 다름 -> Scale에 따른 y값 영향
- Ordinary 또는 Nominal한 값들의 표현은 어떻게?
- 잘못 기입된 값들에 대한 처리
- 값이 없을 경우는 어떻게?
- 극단적으로 큰 값 또는 작은 값들은 그대로 놔둬야 하는가?

## Data preprocessing issues
- 데이터가 빠진 경우(결측치의 처리)
- 라벨링된 데이터(category) 데이터의 처리
- 데이터의 scale의 차이가 매우 크게 날 경우

### Missing Value

#### 데이터가 없을 때 할 수 있는 전략
- 데이터가 없으면 sample을 drop
- 데이터가 없는 최소 개수를 정해서 sample을 drop
- 데이터가 거의 없는 feature는 feature 자체를 drop
- 최빈값, 평균값으로 비어있는 데이터를 채우기

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Eaxmple from - https://chrisalbon.com/python/pandas_missing_data.html
raw_data = {'first_name': ['Jason', np.nan, 'Tina', 'Jake', 'Amy'],
        'last_name': ['Miller', np.nan, 'Ali', 'Milner', 'Cooze'],
        'age': [42, np.nan, 36, 24, 73],
        'sex': ['m', np.nan, 'f', 'm', 'f'],
        'preTestScore': [4, np.nan, np.nan, 2, 3],
        'postTestScore': [25, np.nan, np.nan, 62, 70]}
df = pd.DataFrame(raw_data, columns = ['first_name', 'last_name', 'age', 'sex', 'preTestScore', 'postTestScore'])
df

first_name last_name   age  sex  preTestScore  postTestScore
0      Jason    Miller  42.0    m           4.0           25.0
1        NaN       NaN   NaN  NaN           NaN            NaN
2       Tina       Ali  36.0    f           NaN            NaN
3       Jake    Milner  24.0    m           2.0           62.0
4        Amy     Cooze  73.0    f           3.0           70.0

#### 결측치 확인

In [4]:
df.isnull().sum()

first_name       1
last_name        1
age              1
sex              1
preTestScore     2
postTestScore    2
dtype: int64

In [5]:
df.isnull().sum() / len(df)

first_name       0.2
last_name        0.2
age              0.2
sex              0.2
preTestScore     0.4
postTestScore    0.4
dtype: float64

#### 결측치 제거

In [6]:
df_no_missing = df.dropna()
df_no_missing

first_name last_name   age sex  preTestScore  postTestScore
0      Jason    Miller  42.0   m           4.0           25.0
3       Jake    Milner  24.0   m           2.0           62.0
4        Amy     Cooze  73.0   f           3.0           70.0

In [7]:
df

first_name last_name   age  sex  preTestScore  postTestScore
0      Jason    Miller  42.0    m           4.0           25.0
1        NaN       NaN   NaN  NaN           NaN            NaN
2       Tina       Ali  36.0    f           NaN            NaN
3       Jake    Milner  24.0    m           2.0           62.0
4        Amy     Cooze  73.0    f           3.0           70.0

In [8]:
#모든 데이터가 비어 있으면 drop
df_cleaned = df.dropna(how='all')
df_cleaned

first_name last_name   age sex  preTestScore  postTestScore
0      Jason    Miller  42.0   m           4.0           25.0
2       Tina       Ali  36.0   f           NaN            NaN
3       Jake    Milner  24.0   m           2.0           62.0
4        Amy     Cooze  73.0   f           3.0           70.0

In [10]:
#NAN을 생성 column
df['location'] = np.nan
df

first_name last_name   age  sex  preTestScore  postTestScore  location
0      Jason    Miller  42.0    m           4.0           25.0       NaN
1        NaN       NaN   NaN  NaN           NaN            NaN       NaN
2       Tina       Ali  36.0    f           NaN            NaN       NaN
3       Jake    Milner  24.0    m           2.0           62.0       NaN
4        Amy     Cooze  73.0    f           3.0           70.0       NaN

In [11]:
#column 기준으로 drop
df.dropna(axis=1, how='all')

first_name last_name   age  sex  preTestScore  postTestScore
0      Jason    Miller  42.0    m           4.0           25.0
1        NaN       NaN   NaN  NaN           NaN            NaN
2       Tina       Ali  36.0    f           NaN            NaN
3       Jake    Milner  24.0    m           2.0           62.0
4        Amy     Cooze  73.0    f           3.0           70.0

In [14]:
#데이터가 최소 4개 이상 없을 때 drop
df.dropna(axis=1, thresh=3)

first_name last_name   age  sex  preTestScore  postTestScore
0      Jason    Miller  42.0    m           4.0           25.0
1        NaN       NaN   NaN  NaN           NaN            NaN
2       Tina       Ali  36.0    f           NaN            NaN
3       Jake    Milner  24.0    m           2.0           62.0
4        Amy     Cooze  73.0    f           3.0           70.0

In [15]:
#5개 이상 데이터가 있지 않으면 drop
df.dropna(thresh=5)

first_name last_name   age sex  preTestScore  postTestScore  location
0      Jason    Miller  42.0   m           4.0           25.0       NaN
3       Jake    Milner  24.0   m           2.0           62.0       NaN
4        Amy     Cooze  73.0   f           3.0           70.0       NaN

#### 결측치 대체
- 평균값, 중위값, 최빈값을 활용

In [16]:
#데이터가 없는 곳은 0으로 집어넣어라
df.fillna(0)

first_name last_name   age sex  preTestScore  postTestScore  location
0      Jason    Miller  42.0   m           4.0           25.0       0.0
1          0         0   0.0   0           0.0            0.0       0.0
2       Tina       Ali  36.0   f           0.0            0.0       0.0
3       Jake    Milner  24.0   m           2.0           62.0       0.0
4        Amy     Cooze  73.0   f           3.0           70.0       0.0

In [17]:
df

first_name last_name   age  sex  preTestScore  postTestScore  location
0      Jason    Miller  42.0    m           4.0           25.0       NaN
1        NaN       NaN   NaN  NaN           NaN            NaN       NaN
2       Tina       Ali  36.0    f           NaN            NaN       NaN
3       Jake    Milner  24.0    m           2.0           62.0       NaN
4        Amy     Cooze  73.0    f           3.0           70.0       NaN

In [21]:
#preTestScore의 평균값을 집어넣어라
df["preTestScore"].fillna(df["preTestScore"].mean(), inplace=True)
df

first_name last_name   age  sex  preTestScore  postTestScore  location
0      Jason    Miller  42.0    m           4.0           25.0       NaN
1        NaN       NaN   NaN  NaN           3.0            NaN       NaN
2       Tina       Ali  36.0    f           3.0            NaN       NaN
3       Jake    Milner  24.0    m           2.0           62.0       NaN
4        Amy     Cooze  73.0    f           3.0           70.0       NaN

In [24]:
df.groupby("sex")["postTestScore"].mean()

sex
f    70.0
m    43.5
Name: postTestScore, dtype: float64

In [25]:
df.groupby("sex")["postTestScore"].transform("mean")

0    43.5
1     NaN
2    70.0
3    43.5
4    70.0
dtype: float64

In [26]:
#성별로 나눠서 평균값을 집어넣어라
df["postTestScore"].fillna(
    df.groupby("sex")["postTestScore"].transform("mean"), inplace=True)
df

first_name last_name   age  sex  preTestScore  postTestScore  location
0      Jason    Miller  42.0    m           4.0           25.0       NaN
1        NaN       NaN   NaN  NaN           3.0            NaN       NaN
2       Tina       Ali  36.0    f           3.0           70.0       NaN
3       Jake    Milner  24.0    m           2.0           62.0       NaN
4        Amy     Cooze  73.0    f           3.0           70.0       NaN

In [27]:
#Age와 sex가 모두 notnull인 경우에만 표시해라
df[df['age'].notnull() & df['sex'].notnull()]

first_name last_name   age sex  preTestScore  postTestScore  location
0      Jason    Miller  42.0   m           4.0           25.0       NaN
2       Tina       Ali  36.0   f           3.0           70.0       NaN
3       Jake    Milner  24.0   m           2.0           62.0       NaN
4        Amy     Cooze  73.0   f           3.0           70.0       NaN

### Category data

### 이산형 데이터를 어떻게 처리할까?
- 실제 데이터 set의 크기만큼 Binary Feature를 생성

In [28]:
edges = pd.DataFrame({'source': [0, 1, 2],
                   'target': [2, 2, 3],
                       'weight': [3, 4, 5],
                       'color': ['red', 'blue', 'blue']})

edges

color  source  target  weight
0   red       0       2       3
1  blue       1       2       4
2  blue       2       3       5

In [29]:
edges.dtypes

color     object
source     int64
target     int64
weight     int64
dtype: object

In [30]:
edges["color"]

0     red
1    blue
2    blue
Name: color, dtype: object

In [31]:
pd.get_dummies(edges)

source  target  weight  color_blue  color_red
0       0       2       3         0.0        1.0
1       1       2       4         1.0        0.0
2       2       3       5         1.0        0.0

In [32]:
pd.get_dummies(edges["color"])

blue  red
0   0.0  1.0
1   1.0  0.0
2   1.0  0.0

#### One Hot Encoding

In [33]:
weight_dict = {3:"M", 4:"L", 5:"XL"}
edges["weight_sign"] = edges["weight"].map(weight_dict)
edges

color  source  target  weight weight_sign
0   red       0       2       3           M
1  blue       1       2       4           L
2  blue       2       3       5          XL

In [36]:
#Ordinary data -> One Hot Encoding
pd.get_dummies(edges).values

array([[ 0.,  2.,  3.,  0.,  1.,  0.,  1.,  0.],
       [ 1.,  2.,  4.,  1.,  0.,  1.,  0.,  0.],
       [ 2.,  3.,  5.,  1.,  0.,  0.,  0.,  1.]])

### 데이터의 구간을 나눠보자

#### Data Binning

In [37]:
# Example from - https://chrisalbon.com/python/pandas_binning_data.html

raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'],
        'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'],
        'name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze', 'Jacon', 'Ryaner', 'Sone', 'Sloan', 'Piger', 'Riani', 'Ali'],
        'preTestScore': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
        'postTestScore': [25, 94, 57, 62, 70, 25, 94, 57, 62, 70, 62, 70]}
df = pd.DataFrame(raw_data, columns = ['regiment', 'company', 'name', 'preTestScore', 'postTestScore'])
df

regiment company      name  preTestScore  postTestScore
0   Nighthawks     1st    Miller             4             25
1   Nighthawks     1st  Jacobson            24             94
2   Nighthawks     2nd       Ali            31             57
3   Nighthawks     2nd    Milner             2             62
4     Dragoons     1st     Cooze             3             70
5     Dragoons     1st     Jacon             4             25
6     Dragoons     2nd    Ryaner            24             94
7     Dragoons     2nd      Sone            31             57
8       Scouts     1st     Sloan             2             62
9       Scouts     1st     Piger             3             70
10      Scouts     2nd     Riani             2             62
11      Scouts     2nd       Ali             3             70

In [39]:
bins = [0, 25, 50, 75, 100] # Define bins as 0 to 25, 25 to 50, 60 to 75, 75 to 100
group_names = ['Low', 'Okay', 'Good', 'Great']
categories = pd.cut(df['postTestScore'], bins, labels=group_names)
categories

0       Low
1     Great
2      Good
3      Good
4      Good
5       Low
6     Great
7      Good
8      Good
9      Good
10     Good
11     Good
Name: postTestScore, dtype: category
Categories (4, object): [Low < Okay < Good < Great]

In [40]:
df['categories'] = pd.cut(df['postTestScore'], bins, labels=group_names)
df

regiment company      name  preTestScore  postTestScore categories
0   Nighthawks     1st    Miller             4             25        Low
1   Nighthawks     1st  Jacobson            24             94      Great
2   Nighthawks     2nd       Ali            31             57       Good
3   Nighthawks     2nd    Milner             2             62       Good
4     Dragoons     1st     Cooze             3             70       Good
5     Dragoons     1st     Jacon             4             25        Low
6     Dragoons     2nd    Ryaner            24             94      Great
7     Dragoons     2nd      Sone            31             57       Good
8       Scouts     1st     Sloan             2             62       Good
9       Scouts     1st     Piger             3             70       Good
10      Scouts     2nd     Riani             2             62       Good
11      Scouts     2nd       Ali             3             70       Good

In [41]:
pd.get_dummies(df)

preTestScore  postTestScore  regiment_Dragoons  regiment_Nighthawks  \
0              4             25                0.0                  1.0   
1             24             94                0.0                  1.0   
2             31             57                0.0                  1.0   
3              2             62                0.0                  1.0   
4              3             70                1.0                  0.0   
5              4             25                1.0                  0.0   
6             24             94                1.0                  0.0   
7             31             57                1.0                  0.0   
8              2             62                0.0                  0.0   
9              3             70                0.0                  0.0   
10             2             62                0.0                  0.0   
11             3             70                0.0                  0.0   

    regiment_Scouts  company_1st  company_2nd  name_Ali  name_Cooze  \
0               0.0          1.0          0.0       0.0         0.0   
1               0.0          1.0          0.0       0.0         0.0   
2               0.0          0.0          1.0       1.0         0.0   
3               0.0          0.0          1.0       0.0         0.0   
4               0.0          1.0          0.0       0.0         1.0   
5               0.0          1.0          0.0       0.0         0.0   
6               0.0          0.0          1.0       0.0         0.0   
7               0.0          0.0          1.0       0.0         0.0   
8               1.0          1.0          0.0       0.0         0.0   
9               1.0          1.0          0.0       0.0         0.0   
10              1.0          0.0          1.0       0.0         0.0   
11              1.0          0.0          1.0       1.0         0.0   

    name_Jacobson        ...         name_Milner  name_Piger  name_Riani  \
0             0.0        ...                 0.0         0.0         0.0   
1             1.0        ...                 0.0         0.0         0.0   
2             0.0        ...                 0.0         0.0         0.0   
3             0.0        ...                 1.0         0.0         0.0   
4             0.0        ...                 0.0         0.0         0.0   
5             0.0        ...                 0.0         0.0         0.0   
6             0.0        ...                 0.0         0.0         0.0   
7             0.0        ...                 0.0         0.0         0.0   
8             0.0        ...                 0.0         0.0         0.0   
9             0.0        ...                 0.0         1.0         0.0   
10            0.0        ...                 0.0         0.0         1.0   
11            0.0        ...                 0.0         0.0         0.0   

    name_Ryaner  name_Sloan  name_Sone  categories_Low  categories_Okay  \
0           0.0         0.0        0.0             1.0              0.0   
1           0.0         0.0        0.0             0.0              0.0   
2           0.0         0.0        0.0             0.0              0.0   
3           0.0         0.0        0.0             0.0              0.0   
4           0.0         0.0        0.0             0.0              0.0   
5           0.0         0.0        0.0             1.0              0.0   
6           1.0         0.0        0.0             0.0              0.0   
7           0.0         0.0        1.0             0.0              0.0   
8           0.0         1.0        0.0             0.0              0.0   
9           0.0         0.0        0.0             0.0              0.0   
10          0.0         0.0        0.0             0.0              0.0   
11          0.0         0.0        0.0             0.0              0.0   

    categories_Good  categories_Great  
0               0.0               0.0  
1               0.0               1.0  
2               1.0

### Label encoding by sklearn
- Scikit-learn의 preprocessing 패키지도 label, one-hot 지원

In [42]:
raw_example = df.as_matrix()
raw_example[:3]

array([['Nighthawks', '1st', 'Miller', 4, 25, 'Low'],
       ['Nighthawks', '1st', 'Jacobson', 24, 94, 'Great'],
       ['Nighthawks', '2nd', 'Ali', 31, 57, 'Good']], dtype=object)

In [43]:
data = raw_example.copy()

In [44]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder() #Encoder 생성
le.fit(raw_example[:,0])          #Data에 맞게 encoding fitting
le.transform(raw_example[:,0])    #실제 데이터 -> labelling data

hello

0
0


array([1, 1, 1, 1, 0, 0, 0, 0, 2, 2, 2, 2], dtype=int64)

In [45]:
raw_example[:,0]

array(['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons',
       'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts',
       'Scouts'], dtype=object)

In [46]:
le.fit(raw_example[:,0])

LabelEncoder()

In [47]:
le.classes_

array(['Dragoons', 'Nighthawks', 'Scouts'], dtype=object)

In [48]:
data[:,0] = le.transform(raw_example[:,0])
data[:3]

array([[1, '1st', 'Miller', 4, 25, 'Low'],
       [1, '1st', 'Jacobson', 24, 94, 'Great'],
       [1, '2nd', 'Ali', 31, 57, 'Good']], dtype=object)

- Label encoder의 fit과 transform의 과정이 나눠진 이유는 새로운 데이터 입력시, 기존 labelling 규칙을 그대로 적용할 필요가 있음
- Fit은 규칙을 생성하는 과정
- Transform은 규칙을 적용하는 과정
- Fit을 통해 규칙이 생성된 labelencoder는 따로 저장하여 새로운 데이터를 입력할 경우 사용할 수 있음
- Encoder들을 실제 시스템에 사용할 경우 pickle화 필요

In [49]:
label_column = [0,1,2,5]
label_enconder_list = []
for column_index in  label_column:
    le = preprocessing.LabelEncoder()
    le.fit(raw_example[:,column_index])
    data[:,column_index] = le.transform(raw_example[:,column_index])
    label_enconder_list.append(le) #기존 label encoder를 따로 저장
    del le 
data[:3]

array([[1, 0, 4, 4, 25, 2],
       [1, 0, 2, 24, 94, 1],
       [1, 1, 0, 31, 57, 0]], dtype=object)

In [50]:
#저장된 le로 새로운 데이터에 적용
label_enconder_list[0].transform(raw_example[:10,0])

array([1, 1, 1, 1, 0, 0, 0, 0, 2, 2], dtype=int64)

In [51]:
one_hot_enc = preprocessing.OneHotEncoder()
data[:,0].reshape(-1,1)

array([[1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [2],
       [2],
       [2],
       [2]], dtype=object)

In [52]:
one_hot_enc.fit(data[:,0].reshape(-1,1))

OneHotEncoder(categorical_features='all', dtype=<class 'numpy.float64'>,
       handle_unknown='error', n_values='auto', sparse=True)

In [53]:
onehotlabels = one_hot_enc.transform(data[:,0].reshape(-1,1)).toarray()
onehotlabels

array([[ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.]])

### Feature scaling
- Feature간의 최대-최소값의 차이를 맞춘다!
- Min-Max Normalization : 기존 변수에 범위를 새로운 최대-최소로 변경(일반적으로 0과 1사이 값으로 변경함)
- Standardization(Z-score Normalization) : 기존 변수에 범위를 정규 분포로 변환(실제 Min-Max의 값을 모를 때 활용가능)

### Feature scaling with sklearn
- Label encoder와 마찬가지로, sklearn도 feature scale 지원
- MinMaxScaler와 StandardScaler 사용

In [55]:
# code from - http://sebastianraschka.com/Articles/2014_about_feature_scaling.html

import pandas as pd
import numpy as np

df = pd.io.parsers.read_csv(
    'https://raw.githubusercontent.com/rasbt/pattern_classification/master/data/wine_data.csv',
     header=None,
     usecols=[0,1,2]
    )

df.columns=['Class label', 'Alcohol', 'Malic acid']

df.head()

Class label  Alcohol  Malic acid
0            1    14.23        1.71
1            1    13.20        1.78
2            1    13.16        2.36
3            1    14.37        1.95
4            1    13.24        2.59

In [56]:
std_scale = preprocessing.StandardScaler().fit(
    df[["Alcohol", "Malic acid"]])
df_std = std_scale.transform(df[["Alcohol", "Malic acid"]])
df_std[:5]

array([[ 1.51861254, -0.5622498 ],
       [ 0.24628963, -0.49941338],
       [ 0.19687903,  0.02123125],
       [ 1.69154964, -0.34681064],
       [ 0.29570023,  0.22769377]])

- Preprocessing은 모두 fit -> transform의 과정을 거침, 이유는 label encoder와 동일
- 단, scaler는 한번에 여러 colum을 처리 가능

In [57]:
minmax_scale = preprocessing.MinMaxScaler().fit(df[["Alcohol", "Malic acid"]])
df_minmax = minmax_scale.transform(df[["Alcohol", "Malic acid"]])
df_minmax[:3]

array([[ 0.84210526,  0.1916996 ],
       [ 0.57105263,  0.2055336 ],
       [ 0.56052632,  0.3201581 ]])